export default {
  INTERNAL_SERVER_ERROR:
    "Oops...something went wrong. Please try again or contact support",
  DATA_FETCHED: "Data Fetched",
  AUTH_ERROR: "Authentication Error",
  NO_DATA: "No data Sent",
  KEYS_NOT_MATCH: "keys do not match",
  SERIAL_NO_NOT_FOUND: "Serial Number not registered in CSMS",
  DUPLICATE_RECORD: "Duplicate sent record",
  CREDENTIALS_REQUIRED: "Email and password are required",
  ROLES: {
    CLIENT: "client",
    SUPERADMIN: "superadmin",
  },
  LOGIN_WITH_GOOGLE: "Please login via your Google account",
  LOGIN_WITH_MICROSOFT: "Please login via your Microsoft account",
  STATUS_UPDATED: "Status Updated",
  PROVIDE_ALL_DETAILS: "Please provide all details",
  INVALID_PARAMS: "Invalid parameters",
  NOT_FOUND: "Not Found",
  CANT_BE_EMPTY_STRING: "can't be empty string",
  DELETED: "Deleted",
  IS_MANDATORY_FIELD: "is mandatory field",
  USER_TYPES: {
    ADMIN: "admin",
    APP: "app",
  },
  CREATED: "Created",
  UPDATED: "Updated",
  WEBHOOK_CREATED: "webhook created",
  SSO_METHODS: {
    GOOGLE: "google",
    MICROSOFT: "microsoft",
  },
  INVALID_CREDENTIALS: "invalid credentials",
  LOCATION_CREATED: "location created",
  LOCATION_DELETED: "location deleted",
  PLEASE_PROVIDE_VALID: "Please provide valid",
  STATUS: ["active", "inactive"],
  USER_CREATED: "User created",
  USER_SIGNIN: "User signed In",
  USER_NOT_FOUND: "User not found",
  USER_LOGGED_IN: "User logged in",
  INVALID_PASSWORD: "password is invalid",
  CREDS_REQUIRED: "Username and password are required",
  SIGNED_OUT: "You've been signed out!",
  PASSWORD_REQUIRED: "Old and new password are required to change password",
  PASSWORD_UPDATED: "Password updated successfully.",
  USER_DELETED: "User deleted successfully",
  SUPER_ADMIN_ROLE_REQUIRED: "Super Admin role required!",
  CLIENT_ROLE_REQUIRED: "Client role required!",
  SUPER_ADMIN_OR_CLIENT_ROLE_REQUIRED: "Super Admin or Client role required!",
};
