export default {
  INTERNAL_SERVER_ERROR:
    "Oops...something went wrong. Please try again or contact support",
  DATA_FETCHED: "Data Fetched",
  AUTH_ERROR: "Authentication Error",
  NO_DATA: "No data Sent",
  KEYS_NOT_MATCH: "keys do not match",
  SERIAL_NO_NOT_FOUND: "Serial Number not registered in CSMS",
  DUPLICATE_RECORD: "Duplicate sent record",
  CREDENTIALS_REQUIRED: "Email and password are required",
  ROLES: {
    USER: "user",
    ADMIN: "admin",
  },
  LOGIN_WITH_GOOGLE: "Please login via your Google account",
  LOGIN_WITH_MICROSOFT: "Please login via your Microsoft account",
  STATUS_UPDATED: "Status Updated",
  PROVIDE_ALL_DETAILS: "Please provide all details",
  INVALID_PARAMS: "Invalid parameters",
  NOT_FOUND: "Not Found",
  CANT_BE_EMPTY_STRING: "can't be empty string",
  DELETED: "Deleted",
  IS_MANDATORY_FIELD: "is mandatory field",
  USER_TYPES: {
    ADMIN: "admin",
    APP: "app",
  },
  CREATED: "Created",
  UPDATED: "Updated",
  WEBHOOK_CREATED: "webhook created",
  SSO_METHODS: {
    GOOGLE: "google",
    MICROSOFT: "microsoft",
  },
};
